config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/destroy'

  get 'users/new'

  get 'users/create'

  root 'cities#index'

    resources :cities, only: [:index, :new, :create, :show] do
    resources :lists, only: [:show, :new, :create] do
    resources :descriptions, only: [:show, :new, :create] do
    resources :images, only: [:show, :new, :create]
  end
end
end

resources :users, except: [:edit, :update, :destroy, :show]
  resources :sessions, only: [:new, :create]

  delete 'sign_out' => 'sessions#destroy'

end

app/models/city.rb
class City < ActiveRecord::Base
	has_many :lists
end

app/models/description.rb
class Description < ActiveRecord::Base
  belongs_to :list
  has_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :Description
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :city
  has_many :descriptions
end

app/models/user.rb
class User < ActiveRecord::Base
	  validates :email, presence: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def signed_in?
    current_user.present?
  end

  def current_user
    if session[:user_id]
      user = User.find(session[:user_id])
    else
      nil
    end
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
  	@cities = City.all
  end

  # this methods (and in the other controllers, too) should use a `before_action`
  # to make sure that the request is coming from a signed in user
  def create
  	@city = City.new(cities_params)


	    if @city.save
	      redirect_to cities_path, notice: 'Created!'
	    else
	      render 'new'
	    end
  end

  def show
    @city = City.find(params[:id])
  end

  def new
  	@city = City.new
  end

  private

  def cities_params
    params.require(:city).permit(:image_url, :name)
  end

end

app/controllers/descriptions_controller.rb
class DescriptionsController < ApplicationController
	before_action :lookup_list

  def show
  	@description = @list.descriptions.find(params[:id])
    @first = 0
    @firstImage = ''
  end

  def create
  	@description = @list.descriptions.new(description_params)


	    if @description.save
	      redirect_to city_list_path(@list.city, @list), notice: 'Created!'
	    else
	      render 'new'
	    end
  end

  def new
  	@description = @list.descriptions.new
  end

  private

  def description_params
    params.require(:description).permit(:name, :subtitle,:subtitulo,:detail, :detalhe, :address, :priceRange, :list_id)
  end  

  def lookup_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	before_action :lookup_description

  def show
  end

  def create
  	@image = @desc.images.new(image_params)


	    if @image.save
	      redirect_to cities_path, notice: 'Created!'
	    else
	      render 'new'
	    end
  end

  def new
  	@image = @desc.images.new
  end

  private

  def image_params
    params.require(:image).permit(:image_url, :description_id)
  end  

  def lookup_description
    @desc = Description.find(params[:description_id])
  end
end

app/controllers/list_desctiption_controller.rb
# Is this controller used?
class ListDesctiptionController < ApplicationController
  def show
  	@listsDescription = List.find(params[:id]).descriptions.all.order('name DESC')
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :lookup_city

  def show
  	@lists = @city.lists.find(params[:id])
  end

  def create
  	@list = @city.lists.new(list_params)


	    if @list.save
	      redirect_to cities_path, notice: 'Created!'
	    else
	      render 'new'
	    end
  end

  def new
  	@list = @city.lists.new
  end

  private

  def list_params
    params.require(:list).permit(:name, :nome, :image_url, :city_id)
  end  

  def lookup_city
    @city = City.find(params[:city_id])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Welcome!'
    else
      redirect_to new_session_path, notice: 'Sorry, password and email doesnt match!'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: 'Thank you!'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: 'Thanks for signing up!'
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/descriptions_helper.rb
module DescriptionsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/list_desctiption_helper.rb
module ListDesctiptionHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/_form.html.erb
<%= form_for([@city]) do |c| %>
	<h1>New city</h1>	
  <%= c.label :name %>
  <br>
  <%= c.text_field :name, required: true %>
  <br>
  <br>

  <%= c.label :image_url %>
  <br>
  <%= c.text_field :image_url, required: true %>
  <br>
  <br>

  <%= c.submit 'Save!' %>
<% end %>

app/views/cities/index.html.erb
<div id="wrapper">
	<div id="header">
		<div id="logo"><%= image_tag("/seedImages/logo-urbanlists.png", :alt => "Logo", :id => "indexImg") %></div>
	</div>

	<div id="cityBodyShow">
		<div id="logoTop"><%= image_tag("/seedImages/logo-urbanlists.png", :alt => "Logo", size: "160x100") %></div>
		
		<% @cities.each do |city| %>
		<ul class="img-list">
  			<li>
		    <%= image_tag(city.image_url, size: "640x400") %><Br/>
		    <span class="text-content"><%= link_to city.name, city_path(city), :class => "link-inside-img"%></span>
			</li>
		</ul>
		<%end%>

		<Br/>
		<% if signed_in? %>
		<%= link_to 'New city', new_city_path %>
		<%end%>
	</div>


	<script type="text/javascript" src=""></script>
</div>

app/views/cities/new.html.erb
<div id="formHeader">
	<div id="logoTop"><%= image_tag("/seedImages/logo-urbanlists.png", :alt => "Logo", size: "160x100") %></div>
	<%= link_to 'Back', cities_path %>
</div>
<div id="formBody">
	<%= render 'form' %>
</div>

app/views/cities/show.html.erb
<div id="cityBody">
	<%= link_to 'Back', cities_path%>
	<br/>
	<div class="txt-en">		
			<% @city.lists.each do |list| %>
			<ul class="demo-2 effect">
					<li><a class="zero"><%= list.name %></a></li>
					<li><%= link_to image_tag(list.image_url, size: "300x180", :class => "top" ), city_list_path(@city, list) %><Br/></li>
			</ul>
			<%end%>
	</div>

	<div class="txt-pt">
			<% @city.lists.each do |list| %>
			<ul class="demo-2 effect">
					<li><a class="zero"><%= list.nome %></a></li>
					<li><%= link_to image_tag(list.image_url, size: "300x180", :class => "top" ), city_list_path(@city, list) %><Br/></li>
			</ul>
			<%end%>
	</div>

	<Br/>
	<% if signed_in? %>
	<%= link_to 'New List', new_city_list_path(@city) %>
	<%end%>
</div>

app/views/descriptions/_form.html.erb
<%= form_for([@list.city, @list, @description]) do |d| %>
  <h1>New Item</h1>	
  <%= d.label :name %>
  <br>
  <%= d.text_field :name, required: true %>
  <br>

  <%= d.label :subtitle %>
  <br>
  <%= d.text_field :subtitle, required: true %>
  <br>

  <%= d.label :subtitulo %>
  <br>
  <%= d.text_field :subtitulo, required: true %>
  <br>

  <%= d.label :address %>
  <br>
  <%= d.text_field :address, required: true %>
  <br>

  <%= d.label :detail %>
  <br>
  <%= d.text_area :detail %>
  <br>
  <br>

  <%= d.label :detalhe %>
  <br>
  <%= d.text_area :detalhe %>
  <br>
  <br>

  <%= d.label :priceRange %>
  <br>
  <%= d.text_field :priceRange, required: true %>
  <br>

  <%= d.submit 'Save!' %>
<% end %>

app/views/descriptions/create.html.erb
<h1>Descriptions#create</h1>
<p>Find me in app/views/descriptions/create.html.erb</p>

app/views/descriptions/new.html.erb
<div id="formHeader">
	<div id="logoTop"><%= image_tag("/seedImages/logo-urbanlists.png", :alt => "Logo", size: "160x100") %></div>
	<%= link_to 'Back', cities_path %>
</div>
<div id="formBody">
	<%= render 'form' %>
</div>

app/views/descriptions/show.html.erb
<div id="descriptionBody">
	<%= link_to 'Back', city_list_path(@list.city, @list)%>
		<div id="slider">
			<ul class="slides">
				<% @description.images.each do |image| %>
					<% if @first == 0 %>
						<% if image != nil %>
							<% @first = 1 %>
							<% @imageFirst = image %>
						<% end %>
					<% end %>
					<li class="slide"><%= image_tag(image.image_url, size: "640x400")%></li>
				<%end%>
				<% if  @imageFirst != nil  %>
					<li class="slide"><%= image_tag(@imageFirst.image_url, size: "640x400")%></li>
				<% else %>
					<!-- lol -->
					<li class="slide"><%= image_tag('http://media.giphy.com/media/JIJNVViUm4GgU/giphy.gif', size: "640x400")%></li>
				<% end %>
			</ul>
	    </div>
	<div class="txt-en">
		<h1 id="descriptionName"><%= @description.name %></h1>
		<h2 id="descriptionSubtitle"><%= @description.subtitle %></h2>

		<!--
			Woah, complex!  How about...

			<div id="priceRange"><%= '$' * description.priceRange %></div>

		-->


	    <% if @description.priceRange == 5 %>
			<div id="priceRange">$$$$$</div>
		<% else %>
			<% if @description.priceRange == 4 %>
				<div id="priceRange">$$$$</div>
			<% else %>
				<% if @description.priceRange == 3 %>
					<div id="priceRange">$$$</div>
				<% else %>
					<% if @description.priceRange == 2 %>
						<div id="priceRange">$$</div>
					<% else %>
						<% if @description.priceRange == 1 %>
							<div id="priceRange">$</div>
						<% else %>
							<div id="priceRange"></div>
						<% end %>
					<% end %>
				<% end %>
			<% end %>
		<% end %>

			<p id="detail"><%= @description.detail %></p>

		<h2 id="adress"><%= @description.address %></h2>
		<Br/>
		<%= link_to 'Add your own image!', new_city_list_description_image_path(@list.city, @list, @description) %>
	</div>

	<div class="txt-pt">
		<h1 id="descriptionName"><%= @description.name %></h1>
		<h2 id="descriptionSubtitle"><%= @description.subtitulo %></h2>

	    <% if @description.priceRange == 5 %>
			<div id="priceRange">$$$$$</div>
		<% else %>
			<% if @description.priceRange == 4 %>
				<div id="priceRange">$$$$</div>
			<% else %>
				<% if @description.priceRange == 3 %>
					<div id="priceRange">$$$</div>
				<% else %>
					<% if @description.priceRange == 2 %>
						<div id="priceRange">$$</div>
					<% else %>
						<% if @description.priceRange == 1 %>
							<div id="priceRange">$</div>
						<% else %>
							<div id="priceRange"></div>
						<% end %>
					<% end %>
				<% end %>
			<% end %>
		<% end %>

			<p id="detail"><%= @description.detalhe %></p>

		<h2 id="adress"><%= @description.address %></h2>

		<Br/>
		<%= link_to 'Adicione sua imagem!', new_city_list_description_image_path(@list.city, @list, @description) %>
	</div>



</div>

app/views/images/_form.html.erb
<%= form_for([@desc.list.city, @desc.list, @desc, @image]) do |d| %>
  <h1>New Image</h1>	
  <%= d.label :image_url %>
  <br>
  <%= d.text_field :image_url, required: true %>
  <br>

  <%= d.submit 'Save!' %>
<% end %>

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/images/new.html.erb
<div id="formHeader">
	<div id="logoTop"><%= image_tag("/seedImages/logo-urbanlists.png", :alt => "Logo", size: "160x100") %></div>
	<%= link_to 'Back', cities_path %>
</div>
<div id="formBody">
	<%= render 'form' %>
</div>

app/views/images/show.html.erb
<h1>Images#show</h1>
<p>Find me in app/views/images/show.html.erb</p>

app/views/list_desctiption/show.html.erb
<h1>ListDesctiption#show</h1>
<p>Find me in app/views/list_desctiption/show.html.erb</p>

<% @listsDescription.each do |ld| %>
	<%= link_to ld.name, city_description_path(ld) %>
<% end %>

app/views/lists/_form.html.erb
<%= form_for([@city, @list]) do |l| %>
  <h1>New List</h1>	
  <%= l.label :name %>
  <br>
  <%= l.text_field :name, required: true %>
  <br>
  <%= l.label :nome %>
  <br>
  <%= l.text_field :nome, required: true %>
  <br>
  <%= l.label :image_url %>
  <br>
  <%= l.text_field :image_url, required: true %>
  <br>
  <br>

  <%= l.submit 'Save!' %>
<% end %>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/new.html.erb
<div id="formHeader">
	<div id="logoTop"><%= image_tag("/seedImages/logo-urbanlists.png", :alt => "Logo", size: "160x100") %></div>
	<%= link_to 'Back', city_path(@list.city) %>
</div>
<div id="formBody">
	<%= render 'form' %>
</div>

app/views/lists/show.html.erb
<div id="cityBody">
	<%= link_to 'Back', city_path(@city)%>
	<div class="txt-en">
		<% @lists.descriptions.each do |desc| %>	
		<div id="listBtn">
			<h2><%= link_to desc.name, city_list_description_path(@lists.city, @lists, desc), :class => "linkToDescription" %></h2>
			<p id="listSubtitle"><%= desc.subtitle %></p>
		</div>
		<%end%>
	</div>
	<div class="txt-pt">
		<% @lists.descriptions.each do |desc| %>	
		<div id="listBtn">
			<h2><%= link_to desc.name, city_list_description_path(@lists.city, @lists, desc), :class => "linkToDescription" %></h2>
			<p id="listSubtitle"><%= desc.subtitulo %></p>
		</div>
		<%end%>
	</div>

	<Br/>
	<% if signed_in? %>
	<%= link_to 'New Item', new_city_list_description_path(@lists.city, @lists) %>
	<%end%>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br><br>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <br><br>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit %>

<% end %>