config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/destroy'

  get 'users/new'

  get 'users/create'

  root 'cities#index'

    resources :cities, only: [:index, :new, :create, :show] do
    resources :lists, only: [:show, :new, :create] do
    resources :descriptions, only: [:show, :new, :create] do
    resources :images, only: [:show, :new, :create]
  end
end
end

resources :users, except: [:edit, :update, :destroy, :show]
  resources :sessions, only: [:new, :create]

  delete 'sign_out' => 'sessions#destroy'

end

app/models/city.rb
class City < ActiveRecord::Base
	has_many :lists
end

app/models/description.rb
class Description < ActiveRecord::Base
  belongs_to :list
  has_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :Description
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :city
  has_many :descriptions
end

app/models/user.rb
class User < ActiveRecord::Base
	  validates :email, presence: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def signed_in?
    current_user.present?
  end

  def current_user
    if session[:user_id]
      user = User.find(session[:user_id])
    else
      nil
    end
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
  	@cities = City.all
  end

  # this methods (and in the other controllers, too) should use a `before_action`
  # to make sure that the request is coming from a signed in user
  def create
  	@city = City.new(cities_params)


	    if @city.save
	      redirect_to cities_path, notice: 'Created!'
	    else
	      render 'new'
	    end
  end

  def show
    @city = City.find(params[:id])
  end

  def new
  	@city = City.new
  end

  private

  def cities_params
    params.require(:city).permit(:image_url, :name)
  end

end

app/controllers/descriptions_controller.rb
class DescriptionsController < ApplicationController
	before_action :lookup_list

  def show
  	@description = @list.descriptions.find(params[:id])
    @first = 0
    @firstImage = ''
  end

  def create
  	@description = @list.descriptions.new(description_params)


	    if @description.save
	      redirect_to city_list_path(@list.city, @list), notice: 'Created!'
	    else
	      render 'new'
	    end
  end

  def new
  	@description = @list.descriptions.new
  end

  private

  def description_params
    params.require(:description).permit(:name, :subtitle,:subtitulo,:detail, :detalhe, :address, :priceRange, :list_id)
  end  

  def lookup_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	before_action :lookup_description

  def show
  end

  def create
  	@image = @desc.images.new(image_params)


	    if @image.save
	      redirect_to cities_path, notice: 'Created!'
	    else
	      render 'new'
	    end
  end

  def new
  	@image = @desc.images.new
  end

  private

  def image_params
    params.require(:image).permit(:image_url, :description_id)
  end  

  def lookup_description
    @desc = Description.find(params[:description_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :lookup_city

  def show
  	@lists = @city.lists.find(params[:id])
  end

  def create
  	@list = @city.lists.new(list_params)


	    if @list.save
	      redirect_to cities_path, notice: 'Created!'
	    else
	      render 'new'
	    end
  end

  def new
  	@list = @city.lists.new
  end

  private

  def list_params
    params.require(:list).permit(:name, :nome, :image_url, :city_id)
  end  

  def lookup_city
    @city = City.find(params[:city_id])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Welcome!'
    else
      redirect_to new_session_path, notice: 'Sorry, password and email doesnt match!'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: 'Thank you!'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: 'Thanks for signing up!'
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/descriptions_helper.rb
module DescriptionsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/list_desctiption_helper.rb
module ListDesctiptionHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrbanList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="margin: 0;">
	<div id="header1">
		<a href="#" id= "select-language" class="select-en"><img src="http://www.icicp.org/wp-content/uploads/2014/02/uk-flag.jpg" alt="uk" height="20" width="32"></a>
		<a href="#" id= "select-language" class="select-pt"><img src="http://www.worldatlas.com/webimage/flags/countrys/zzzflags/brlarge.gif" alt="br" height="20" width="32"></a>

		<h3 id="notice"><%= flash[:notice] %></h3>
		<% if signed_in? %>
		  <h3 id ="userName"><%= current_user.name %></h3>

		  <%= link_to 'Sign out', sign_out_path, method: :delete%>
		  <p><%= link_to 'Create a new user', new_user_path%></p>
		<% else %>
		  
		  <p><%= link_to 'Sign in', new_session_path%></p>
		<% end %>
	</div>
		
	<%= yield %>


</body>
</html>